#- name: Payment Setting
#  hosts: all
#  become: yes
#  vars:
#    component: payment
#  tasks:
#    - name:  Setup Python
#      ansible.builtin.import_tasks: python.yml


- name: Dispatch Setting
  hosts: all
  become: yes
  vars:
    component: dispatch
  tasks:
    - name:  Setup golang
      ansible.builtin.import_tasks: golang.yml

- name: Validate Dispatch details
  ansible.builtin.shell: tail -f /var/log/messages