- name: Install Python
  ansible.builtin.yum:
    name:
      - python36
      - gcc
      - pyhton3-devel
    state: installed

- name: App Pre-requisites
  ansible.builtin.import_tasks: app-preq.yml

- name: Download Python Dependencies
  ansible.builtin.shell: pip3.6 install -r requirements
  args:
    chdir: /app

- name: Systemd Setup
  ansible.builtin.import_tasks: systemd-setup.yml